name: Run test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install mocha
      run: npm install -g mocha

    - name: Install dependencies
      run: npm install

    - name: Run Test
      run: npm run test

    - name: Show report
      run: cat ./test-results.txt